__all__= ['test_command_checker02',
'sample_proc_checker',
'sample_proc',
'test_ext_procedure_for_db_021',
'get_license_ID_from_db_021',
'clear_all_events_021',
'clear_all_passwords_021',
'set_deleted_021',
'add_client_021',
'clear_all_clients_021',
]
